services:
  forcedfr:
    image: forcedfr:latest
    container_name: forcedfr
    restart: unless-stopped

    ports:
      - "8798:8798"

    environment:
      QB_HOST: ${QB_HOST}
      QB_USERNAME: ${QB_USERNAME}
      QB_PASSWORD: ${QB_PASSWORD}
      TZ: Europe/Paris

    volumes:
      - "/media/Films:/media/Films:rw"
      - "/media/Séries:/media/Séries:rw"
